### ISSUE TITLE
where is options?

### ISSUE THREAD

**Issue by m7md3omr** [jestov/grid-gallery#1]
Hello , 
thanks for the great stuff , i 've used it and it quite and clean :) 
is there any option object , that i can pass properties in to control some aspects for this gallery, something like number of images in rows , or the width of the images and so on .
that would be a great addition.

**Comment by jestov** [comment]
Hi. I have added some features to the gallery with your recommendation, now you can customize the width and length of the images and the space between them. I also added a dark mode for the gallery and different types of layouts, you can check the docs on the readme.

I hope the addition is helpful!
