### ISSUE TITLE
Navigation buttons bug (2 images only)

### ISSUE THREAD

**Issue by alnidok** [jestov/grid-gallery#2]
If we have 2 images in gallery
```
<div class="gg-box">
    <img src="img/1.jpg">
    <img src="img/2.jpg">
</div>
```
and then:
1) open first image and click next button (prev button is hiding but it should not)
2) open last image and click prev button (next button is hiding but it should not)

**Comment by jestov** [comment]
Thanks for detect it. I have merged your contribution!
